create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.settings (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  gym_detection_radius integer not null default 200 check (gym_detection_radius > 0),
  theme text not null default 'dark' check (theme in ('dark')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id),
  unique (id, user_id)
);

create table public.body_part_groups (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null check (btrim(name) <> ''),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, user_id)
);

create unique index body_part_groups_user_name_idx
  on public.body_part_groups (user_id, lower(name));

create table public.gyms (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null check (btrim(name) <> ''),
  abbreviation text not null check (btrim(abbreviation) <> ''),
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, user_id)
);

create unique index gyms_user_name_idx on public.gyms (user_id, lower(name));
create unique index gyms_user_abbreviation_idx on public.gyms (user_id, lower(abbreviation));

create table public.exercises (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  body_part_group_id bigint not null,
  name text not null check (btrim(name) <> ''),
  machine boolean not null default false,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, user_id),
  foreign key (body_part_group_id, user_id)
    references public.body_part_groups(id, user_id)
    on delete restrict
);

create unique index exercises_user_name_idx on public.exercises (user_id, lower(name));
create index exercises_body_part_group_idx on public.exercises (body_part_group_id);

create table public.workouts (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  gym_id bigint,
  start_time timestamptz not null,
  end_time timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, user_id),
  check (end_time is null or end_time >= start_time),
  foreign key (gym_id, user_id)
    references public.gyms(id, user_id)
    on delete set null (gym_id)
);

create index workouts_user_start_time_idx on public.workouts (user_id, start_time desc);
create index workouts_open_idx on public.workouts (user_id, start_time desc) where end_time is null;

create table public.workout_exercises (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  workout_id bigint not null,
  exercise_id bigint not null,
  exercise_order integer not null check (exercise_order >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, user_id),
  unique (workout_id, exercise_id),
  unique (workout_id, exercise_order),
  foreign key (workout_id, user_id)
    references public.workouts(id, user_id)
    on delete cascade,
  foreign key (exercise_id, user_id)
    references public.exercises(id, user_id)
    on delete restrict
);

create index workout_exercises_exercise_idx on public.workout_exercises (exercise_id);

create table public.workout_sets (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  workout_exercise_id bigint not null,
  set_number integer not null check (set_number > 0),
  weight numeric(8, 3) not null check (weight >= 0),
  reps integer not null check (reps > 0),
  performed_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, user_id),
  unique (workout_exercise_id, set_number),
  foreign key (workout_exercise_id, user_id)
    references public.workout_exercises(id, user_id)
    on delete cascade
);

create index workout_sets_performed_at_idx
  on public.workout_sets (workout_exercise_id, performed_at);

create trigger settings_set_updated_at
before update on public.settings
for each row execute function public.set_updated_at();

create trigger body_part_groups_set_updated_at
before update on public.body_part_groups
for each row execute function public.set_updated_at();

create trigger gyms_set_updated_at
before update on public.gyms
for each row execute function public.set_updated_at();

create trigger exercises_set_updated_at
before update on public.exercises
for each row execute function public.set_updated_at();

create trigger workouts_set_updated_at
before update on public.workouts
for each row execute function public.set_updated_at();

create trigger workout_exercises_set_updated_at
before update on public.workout_exercises
for each row execute function public.set_updated_at();

create trigger workout_sets_set_updated_at
before update on public.workout_sets
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.settings (user_id) values (new.id)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

insert into public.settings (user_id)
select id from auth.users
on conflict (user_id) do nothing;

alter table public.settings enable row level security;
alter table public.body_part_groups enable row level security;
alter table public.gyms enable row level security;
alter table public.exercises enable row level security;
alter table public.workouts enable row level security;
alter table public.workout_exercises enable row level security;
alter table public.workout_sets enable row level security;

create policy "Users manage own settings"
on public.settings for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users manage own body part groups"
on public.body_part_groups for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users manage own gyms"
on public.gyms for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users manage own exercises"
on public.exercises for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users manage own workouts"
on public.workouts for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users manage own workout exercises"
on public.workout_exercises for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users manage own workout sets"
on public.workout_sets for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

revoke all on table public.settings from anon;
revoke all on table public.body_part_groups from anon;
revoke all on table public.gyms from anon;
revoke all on table public.exercises from anon;
revoke all on table public.workouts from anon;
revoke all on table public.workout_exercises from anon;
revoke all on table public.workout_sets from anon;

grant select, insert, update, delete on table public.settings to authenticated;
grant select, insert, update, delete on table public.body_part_groups to authenticated;
grant select, insert, update, delete on table public.gyms to authenticated;
grant select, insert, update, delete on table public.exercises to authenticated;
grant select, insert, update, delete on table public.workouts to authenticated;
grant select, insert, update, delete on table public.workout_exercises to authenticated;
grant select, insert, update, delete on table public.workout_sets to authenticated;

grant usage, select on sequence public.settings_id_seq to authenticated;
grant usage, select on sequence public.body_part_groups_id_seq to authenticated;
grant usage, select on sequence public.gyms_id_seq to authenticated;
grant usage, select on sequence public.exercises_id_seq to authenticated;
grant usage, select on sequence public.workouts_id_seq to authenticated;
grant usage, select on sequence public.workout_exercises_id_seq to authenticated;
grant usage, select on sequence public.workout_sets_id_seq to authenticated;

revoke execute on function public.set_updated_at() from public, anon, authenticated;
revoke execute on function public.handle_new_user() from public, anon, authenticated;