create table public.strava_connections (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  strava_athlete_id bigint not null,
  strava_athlete_name text,
  scope text not null check (btrim(scope) <> ''),
  access_token text not null,
  refresh_token text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id),
  unique (strava_athlete_id)
);

create trigger strava_connections_set_updated_at
before update on public.strava_connections
for each row execute function public.set_updated_at();

create table public.strava_activities (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  strava_activity_id bigint not null,
  name text not null check (btrim(name) <> ''),
  sport_type text,
  start_date timestamptz not null,
  elapsed_time_seconds integer check (elapsed_time_seconds is null or elapsed_time_seconds >= 0),
  moving_time_seconds integer check (moving_time_seconds is null or moving_time_seconds >= 0),
  distance_meters numeric check (distance_meters is null or distance_meters >= 0),
  elevation_gain_meters numeric check (elevation_gain_meters is null or elevation_gain_meters >= 0),
  raw_payload jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, strava_activity_id)
);

create index strava_activities_user_start_date_idx
  on public.strava_activities (user_id, start_date desc);

create index strava_activities_user_sport_type_idx
  on public.strava_activities (user_id, sport_type);

create trigger strava_activities_set_updated_at
before update on public.strava_activities
for each row execute function public.set_updated_at();

alter table public.strava_connections enable row level security;
alter table public.strava_activities enable row level security;

-- OAuth tokens are server-only. Edge Functions use the service role to access this table.
revoke all on table public.strava_connections from anon, authenticated;

-- Imported activity metadata is readable by the owner; writes remain server-only.
revoke all on table public.strava_activities from anon;
grant select on table public.strava_activities to authenticated;

grant usage, select on sequence public.strava_connections_id_seq to service_role;
grant usage, select on sequence public.strava_activities_id_seq to service_role;
grant select, insert, update, delete on table public.strava_connections to service_role;
grant select, insert, update, delete on table public.strava_activities to service_role;

create policy "Allowed user reads own Strava activities"
on public.strava_activities for select to authenticated
using ((select public.is_allowed_user()) and (select auth.uid()) = user_id);
