create table public.strava_connections (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  strava_athlete_id bigint not null,
  strava_athlete_name text,
  scope text not null check (btrim(scope) <> ''),
  access_token text not null,
  refresh_token text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id),
  unique (strava_athlete_id)
);

create trigger strava_connections_set_updated_at
before update on public.strava_connections
for each row execute function public.set_updated_at();

alter table public.strava_connections enable row level security;

-- OAuth tokens are server-only. Edge Functions use the service role to access this table.
revoke all on table public.strava_connections from anon, authenticated;

grant usage, select on sequence public.strava_connections_id_seq to service_role;
grant select, insert, update, delete on table public.strava_connections to service_role;
