create table public.workout_strava_links (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  workout_id bigint not null,
  strava_activity_id bigint not null,
  created_at timestamptz not null default now(),
  unique (workout_id),
  unique (user_id, strava_activity_id),
  foreign key (workout_id, user_id)
    references public.workouts(id, user_id)
    on delete cascade
);

alter table public.workout_strava_links enable row level security;
revoke all on table public.workout_strava_links from anon;
grant select on table public.workout_strava_links to authenticated;
grant select, insert, update, delete on table public.workout_strava_links to service_role;
grant usage, select on sequence public.workout_strava_links_id_seq to service_role;

create policy "Allowed user reads own Strava workout links"
on public.workout_strava_links for select to authenticated
using ((select public.is_allowed_user()) and (select auth.uid()) = user_id);
